# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlamingoFinance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlamingoFinance
  pod 'Parse'
  pod 'AlamofireImage'

  target 'FlamingoFinanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlamingoFinanceUITests' do
    # Pods for testing
  end

end
